services:
  # Frontend (Static Site)
  - type: web
    name: guidetobohol-frontend
    env: static
    rootDir: Frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    
  # Backend (Web Service)  
  - type: web
    name: guidetobohol-backend
    env: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production